### PR TITLE
Fixed issue where text is truncated when client height equals max height

### LINKED ISSUE #46: Text is truncated even though there's enough height to fit
Text was getting truncated even though there's enough height to fit all text. This happens when offsetHeight is exactly equal to maxHeight. On line 43 of shave.js, the comparison should be less than or equal to. I was forced to add an extra pixel to not get my text truncated enough though there's enough space.

### PR DESCRIPTION
**Pull request by qsjchen**
Fixes #46

### CODE REVIEW

**Comment by yowainwright** [comment]
@qsjchen I'll review this tomorrow. THANKS!

**Comment by yowainwright** [comment]
@qsjchen https://github.com/dollarshaveclub/shave/pull/34 Note the hanging chad

**Comment by qsjchen** [comment]
What you mentioned there seems like a separate issue that will be there regardless if you merge it in or not though. Why not fix this issue first?

**Comment by ibarsi** [comment]
I agree with @qsjchen, the comments in #34 don't seem entirely relevant to what this PR is trying to address. That "hanging chad" is there regardless, but even so the ellipses is still within the element's defined width. Its not like its bleeding out the edge of the element. _That_ would be a bigger issue.

**Comment by yowainwright** [comment]
@qsjchen @ibarsi thanks for your comments. 

Your points have been read. 

https://github.com/dollarshaveclub/shave/issues/46
^ Your issues will be addressed here.

**Pull request closed without merging**
