### PR TITLE
Use spaces option if boolean is provided

### PR DESCRIPTION
**Pull request by mattsacks**
When setting the option `spaces` to `false`, it would be ignored due to the default being `true`.

This PR checks to see if a boolean option is provided for spaces and uses that before defaulting to `true`.

### CODE REVIEW

**Comment by yowainwright** [comment]
I might be missing something...but the sentence provided above and the pr logic are incorrect. 

Thanks for taking the time to review the code and submit a PR!

**Comment by yowainwright** [comment]
The code that is there is tested and appears to be working as expected.

If you would like to take the perceived issue to code editing tool, here's a [codepen](https://codepen.io/yowainwright/pen/wzVgMp) with `spaces` set to `false`.

**Comment by mattsacks** [comment]
@yowainwright yep! So there, it looks like it's truncating within the word whereas the desired behavior by setting `opts.spaces = false` would be to split between words. When I changed line 82 between `false` and `true`, I didn't actually see any difference rendered (the original issue my PR attempts to fix).

If you check out [this codepen with the applied fix](https://codepen.io/anon/pen/GGBVqQ), you can see that switching between `spaces: false` and `spaces: true` will change where truncation happens (i.e, after the word `food` and within the word `truck` respectively).

**Comment by mattsacks** [comment]
@yowainwright Yep! That's because there's nothing in the code to `.split(' ')` on ([called when `opts.spaces === false`](https://github.com/dollarshaveclub/shave/blob/4b965c297957efd23e7b700ff7a04626a480f94a/src/shave.js#L27)). So I actually think that's working as intended there?

**Comment by yowainwright** [comment]
@mattsacks darn it! Thank you for taking the time to continually explain this issue. 

You are 100% right! This issue was introduced a while ago too. Do you still want to provide the fix?

**Comment by mattsacks** [comment]
@yowainwright I’d love to!

By re-opening this PR, it looks like it got my update for the proper ternary syntax. Is there anything else you need before this can be merged?

**Comment by yowainwright** [comment]
@mattsacks if you'd like the provid a patch version bump in `package.json` to `2.2.1` and then build (`npm run build`), you're more than welcome to!

Other wise, this is prefect. Thanks again! ...And sorry it took, me a bit see the bug.

**Comment by mattsacks** [comment]
@yowainwright more than happy to, I’ll get that up for you in just a bit.

And no prob! I’m glad we’re able to get this fixed 🙏

**Comment by mattsacks** [comment]
@yowainwright all set!

**Pull request merged**
