### PR TITLE
Add innerHTML option

### PR DESCRIPTION
**Pull request by jethrodew**
I have a use case where my text has anchors in it but because it uses innerText / textContent, it actually removes links and post parsing it is just a nightmare so I added an option to use innerHTML instead.

### CODE REVIEW

**Comment by yowainwright** [comment]
@jethrodew thank you so much for this thoughtful PR. Sorry I didn't see it sooner! Could you write a test in `tests/test.js`?

I will then go through it all to make sure we're fully covered for now **&** then. 😊

**Comment by yowainwright** [comment]
@jethrodew I thought about your scenario more and the `shave` readme notes that shave is for **text content**. If `shave` were to support trimming of html, the plugin would have 2 problems:

1. `html elements` which would not necessarily be `inline` and _could_ have their own styles which would create un-thought-of results defeating the purpose of the plugin.
2. It is a UX problem. If there are html links within the trimmed text, then the links, etc would potential be hidden which mutes the reason for trimming text at all. 

For your scenario, I would suggest 3 things:

1. Remove html from the content of the item you'd like to trim, then trim it.
2. Hide a portion of the text and add _show-more button_.
3. Use [Line Clamp](http://caniuse.com/#feat=css-line-clamp)

What are your thoughts? 

If you agree, we can close this PR, add a note in an issue, and then link to it in the readme.

Thanks again!

**Comment by jethrodew** [comment]
Hey Jeff, I totally understand the issue with this; it's a nasty business with the extra possibilities which obviously couldn't be supported as it would add huge bloat to the project. The problem I have is that if my sample text has a nice simple anchor in it, that gets removed by Shave when it runs so I would have to post process it to add it back in. 

Line Clamp has yet to be properly implemented by Edge and Firefox which is a massive pain so i can't use that route for client reasons. I have implemented a wrapper for my app which gives it the ability to have read more / show less functionality but links that are in the visible portion of text are not clickable even though they were rendered that way. I don't want it to be a cause for efficiency problems, if you feel that it is not suited to Shave, I shall simply add it to my wrapper layer and leave it at that. Thanks for your time and consideration, I absolutely love the simplicity and effectiveness of Shave; keep up the good work!!

**Comment by yowainwright** [comment]
@jethrodew cool! I'm going to close this PR. Please share your implementation—would love to see it! 🙌

**Comment by jethrodew** [comment]
Thanks Jeff!! 👍

**Pull request closed without merging**
