### PR TITLE
Update build to export ES module

### PR DESCRIPTION
**Pull request by awcross**
Adding support for [pkg.module](https://github.com/rollup/rollup/wiki/pkg.module) allowing users to take advantage of modules.

- Added `es` format to rollup config
- Separated jQuery rollup config out from default (keeping naming convention)

### CODE REVIEW

**Comment by awcross** [comment]
@yowainwright My thought by creating `shave.umd.js` was to make it clear what the difference was between the two files. I understand you're reasoning though and I'll work on this a bit more!

**Comment by yowainwright** [comment]
@awcross your thinking on naming is 👍. For a less adopted or internal project, I would agree 100% on the file name change. 

Thanks for your consideration. Looking forward to the update!

**Comment by awcross** [comment]
Thanks, @yowainwright. Let me know if this works.

**Comment by yowainwright** [comment]
@awcross my bad, missed the email will look shortly.

**Pull request merged**
