### PR TITLE
use native Array.from to loop over NodeList

### PR DESCRIPTION
**Pull request by marcobiedermann**
Using Array.from to loop over a NodeList of elements is always faster than using a for loop.

### CODE REVIEW

**Comment by yowainwright** [comment]
Hey @marcobiedermann, thanks for your pr!  💪 

Why do you prefer `Array.from`?  
Do you have any reason to suggest the change?

I going to close the PR because it breaks the build and is not tested but if you have any reason for the change - I'm very interested to understand it. 😊

**Comment by marcobiedermann** [comment]
@yowainwright

Hey Jeff,

The reason because I use `Array.from` is that is allows you to nicely loop over a Node List.
You are getting the elements from the DOM via `document.querySelectorAll` (https://github.com/dollarshaveclub/shave/blob/master/src/shave.js#L4) which returns a Node List instead of an Array.
You could use `Array.prototype.forEach.call(elements, element => { … } )` but this looks a bit hacky to me.
You could also your solution `for (let i = 0; i < elements.length; i++) { elements[i] }` which perfectly works. Using `Array.from` looks and feels a lot cleaner in my opinion and is faster because it uses the native implementation in the JavaScript engine.
I've tested my changes with all your cases in the test file and it works fine.

You / we should still test it against other examples.

The only downside using `Array.from` is that is not supported in IE. I tent to use the latest web standards and provide a polyfill for older browsers.

I know this might be a minor change but when using more than 100 elements, it does have a performance impact.
Nothing that is to noticeable but it is faster and small things add up 😄

**Comment by yowainwright** [comment]
@marcobiedermann thanks for thoughtful considerations. 

I think you're on to something with your _loop_ notes. 💪 We won't be using `Array.from` for a few reasons (I tested your suggestion as well by the way ✔️) but I will attempt to make the for loop more performant tonight. 

Thanks again! I'll @ you with another update soon.

**Comment by marcobiedermann** [comment]
@yowainwright
You are very welcome.
Feel free to hit me up at any time 😄

**Pull request closed without merging**
