### PR TITLE
Add event when contet did shave

### PR DESCRIPTION
**Pull request by ilake**
## Proposed Changes

Dispatch an event when the content did shave.

Because we have a requirement that needs to show/hide the expander depends on the content be shaved or not.

### CODE REVIEW

**Comment by yowainwright** [comment]
Hey @ilake,

Thanks for your thoughtful PR?

The functionality could be provided with the css classes added after text has been shaved using Shave. 

Why won't that work for your project?

**Comment by ilake** [comment]
Hi @yowainwright What I do in the project because we also need the slide animation for the expanding, not simply hide/show, so I think this PR is good enough for us to customize.

**Comment by ilake** [comment]
Hi @yowainwright What I do in the project because we also need the slide animation for the expanding, not simply hide/show, so I think this PR is good enough for us to customize.

**Comment by yowainwright** [comment]
@ilake here's some pseudo code

```javascript

const someCustomLogicIfShaved = () => {}
const dispatchMyShaveEventIfSomeSelectorIsShaved = () => {
 const someSelector = document.querySelectorAll('some selector')
  shave(someSelector)
  const eventName = 'shave:didShave'
  const event = new Event(eventName)
  [...someSelector].forEach( => {
   if (selector.querySelector('.js-shave')) { 
      selector.addEventListener(eventName,  someCustomeLogic, false)
      selector.dispatchEvent(event)
   }
  })
}

```

Something like that will be more maintainable and performant for your use case and for Shave.

**Comment by ilake** [comment]
@yowainwright Ya, the pseudo code is similar to what I do in the project. However, I think it the event more reliable from the library instead of observing a specific class, that is why I submit this PR.

But you thought it is not necessary for `Shave` to send the event to notify outside,
It should be good enough to observe the particular class, right?

**Comment by yowainwright** [comment]
@ilake yes. This a good work but not in line with the project. 🏅 

Thanks for working with me! Would you close this PR?

----

With features such as the ones listed [here](https://github.com/dollarshaveclub/shave#notes), going in the direction of a [state machine](https://www.smashingmagazine.com/2018/01/rise-state-machines/) for a utility like Shave blurs the lines of the convenience problem that shave solves. 

----

Thank you!!!

**Pull request closed without merging**
